### ISSUE TITLE
Positioning is difficult. Please improve.

### ISSUE THREAD

**Issue by JGameMaker92** [microsoft/VisualProfiler-Unity#32]
Can you make it so that this thing will follow a transform instead of automatically only following the main camera? Also the profiler is way too close to my face and I can't adjust how far away it is. Make it easier to look at in VR.

**Comment by Cameron-Micka** [comment]
Hi @JGameMaker92, this is great feedback. I can add an option to follow a transform. Can I ask which VR headset you are using? Also, you can adjust the positioning of the profiler via these settings. Try changing "Window Scale" to make the window appear further from your face.
![image](https://github.com/microsoft/VisualProfiler-Unity/assets/13305729/c9a3997d-b053-478b-b857-551d23b2b147)

**Comment by JS-X-Visual** [comment]
I have the same problem on the Quest3.
Making something smaller is not the same as moving it further away from my eyes in VR. 
It being so close does definitely gives me eye strain when i try to focus on it.

**Comment by Cameron-Micka** [comment]
Thanks for the feedback @JS-X-Visual, I'll try to get to this soon!

**Comment by Cameron-Micka** [comment]
[v3.8.0](https://github.com/microsoft/VisualProfiler-Unity/releases/tag/v3.8.0) has a fix for this. A new property called "TransformToFollow" has been added to allow users to select a transform to follow rather than the main camera. The sample scene has been updated to show off this behavior:
![image](https://github.com/user-attachments/assets/f5a81a8f-1e5d-4133-aa5f-7f50fbdb31de)
