### ISSUE TITLE
Why does gpuFrameRate always be zero?

### ISSUE THREAD

**Issue by yichez16** [microsoft/VisualProfiler-Unity#8]
Dear contributors,

I am working on profiling my MRTK app on Hololens2 by VisualProfiler. I noticed that cpuFrameRate has values ranging from 0 to 60 fps. However, gpuFrameRate is always zero. 
Is that because VisualProfiler can not access the information of GPU rendering?

**Comment by Cameron-Micka** [comment]
Hi @yichez16,

Thank you for opening this issue. You care correct the VisualProfiler doesn't have access to GPU timing on HoloLens 2 because Unity's [Frame Timing Manager](https://docs.unity3d.com/ScriptReference/FrameTimingManager.html) doesn't return timing info for the HoloLens 2 platform. But, I just reached out to my contacts at Unity to see if support for this is in the roadmap.

If this is a blocking issue for you another option is to use our native plugin to get GPU timing stats: https://github.com/microsoft/MixedRealityToolkit/tree/main/GpuStats

**Comment by yichez16** [comment]
Thank you for your detailed explanation.
